server:
  port: 8888                   # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: localhost
    instanceId: localhost:${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/