server:
  port: 9995
  servlet:
    context-path: /m2-member
eureka:
  instance:
    hostname: localhost
    instanceId: localhost:${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: m2-member